### ISSUE TITLE
Exiting a donkey breaks the GUI

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/JukeAlert#15]
```
[16:26:20 ERROR]: Could not pass event InventoryClickEvent to CivModCore v1.7.9                                                                                                                                    
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.DONKEY                                                                                                                                    
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_252]                                                                                                                                                    
        at org.bukkit.Material.valueOf(Material.java:83) ~[patched_1.14.4.jar:git-Paper-243]                                                                                                                       
        at com.untamedears.jukealert.model.actions.impl.ExitVehicleAction.getVehicle(ExitVehicleAction.java:35) ~[?:?]                                                                                             
        at com.untamedears.jukealert.model.actions.impl.ExitVehicleAction.getGUIRepresentation(ExitVehicleAction.java:26) ~[?:?]                                                                                   
        at com.untamedears.jukealert.gui.SnitchLogGUI.constructContent(SnitchLogGUI.java:79) ~[?:?]                                                                                                                
        at com.untamedears.jukealert.gui.SnitchLogGUI.showScreen(SnitchLogGUI.java:160) ~[?:?]                                                                                                                     
        at com.untamedears.jukealert.gui.SnitchOverviewGUI$1.clicked(SnitchOverviewGUI.java:66) ~[?:?]                                                                                                             
        at vg.civcraft.mc.civmodcore.inventorygui.IClickable.onLeftClick(IClickable.java:56) ~[?:?]                                                                                                                
        at vg.civcraft.mc.civmodcore.inventorygui.IClickable.handleClick(IClickable.java:111) ~[?:?]                                                                                                               
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.itemClick(ClickableInventory.java:162) ~[?:?]                                                                                                 
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventoryListener.inventoryClick(ClickableInventoryListener.java:28) ~[?:?]                                                                             
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor114.execute(Unknown Source) ~[?:?]                                                                                           
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]                                                                                              
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]                                                                                             
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]                                                                                          
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]                                                                                       
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2314) ~[?:git-Paper-243]                                                                                                         
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-243]                                                                                              
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-243]                                                                                              
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]                                                        
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]                                                                                                           
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]                                                                             
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]                                                                                 
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]                                                                             
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]                                                                                         
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]                                                                                
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]                                                                              
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]                                                                               
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]                                                                                         
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]                   
```
In this stack someone exited a donkey, which apparently is a vehicle. To log this it saves the material of the entity existed (usually boats and carts), here we need to insert a different material for when someone exists a donkey.  Same for entering most likely.

**Comment by Maxopoly** [comment]
Also needs a fallback thing for fixing existing logs

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/JukeAlert/pull/25
